---
#OS_version: 12.1X44-D20.3
#OS_package: junos-vsrx-12.1X44-D20.3-domestic.tgz

interfaces:
  ge-0/0/1:
    - { vlan: 200, ip_addr: 10.10.200.12/24 }
    - { vlan: 201, ip_addr: 10.10.201.13/24 }
    - { vlan: 307, ip_addr: 10.10.107.129/24 }

zones:
  DMZ:
    interfaces:
      - ge-0/0/1.200
      - ge-0/0/1.201
      - ge-0/0/1.307
